### ISSUE TITLE
Unparse -- symbol cannot be cast

### ISSUE THREAD

**Issue by pmdoll** [dollabs/pamela#147]
For the pamela file as below, unparse command yields exception. 

`pamela -h` is not clear on what the expected input is: pamela vs IR-as-edn. So I tried both without much success. 

```
(defpclass a []
           :fields {fa "fa"}
           :modes {:moa1 (= fa "fa")
                   :moa2 (= fa false)}
           :transitions {
                         :moa1:moa2 {:pre :moa1 :post :moa2
                                     :doc "transition :moa1 -> :moa2"}
                         :moa2:moa1 {:pre :moa2 :post :moa1
                                     :doc "transition :moa2 -> :moa1"}}
           :methods [(defpmethod ma [arg1 arg2])]
           )
```
```
pamela -v -v -i unparse.pamela unparse 
repl?: false
version: nil
verbosity level: 2
log level: :warn
construct-tpn: nil
file-format: json
input: [#object[java.io.File 0x7cfb0c4c /Users/prakash/projects/github/dollabs/pamela/test/pamela/unparse.pamela]]
output: -
source: nil
magic: nil
output-magic: nil
root-task: nil
cmd: unparse (valid)
Exception in thread "main" java.lang.ClassCastException: clojure.lang.Symbol cannot be cast to java.util.Map$Entry
        at clojure.lang.APersistentMap$KeySeq.first(APersistentMap.java:166)
        at clojure.lang.RT.first(RT.java:667)
        at clojure.core$first__4339.invokeStatic(core.clj:55)
        at clojure.core$first__4339.invoke(core.clj:55)
        at pamela.unparser$unparse$iter__1823__1827$fn__1828.invoke(unparser.clj:532)
        at clojure.lang.LazySeq.sval(LazySeq.java:40)
        at clojure.lang.LazySeq.seq(LazySeq.java:49)
        at clojure.lang.RT.seq(RT.java:521)
        at clojure.core$seq__4357.invokeStatic(core.clj:137)
        at clojure.core$interleave$fn__5151.invoke(core.clj:4186)
        at clojure.lang.LazySeq.sval(LazySeq.java:40)
        at clojure.lang.LazySeq.seq(LazySeq.java:49)
        at clojure.lang.Cons.next(Cons.java:39)
        at clojure.lang.RT.boundedLength(RT.java:1749)
        at clojure.lang.RestFn.applyTo(RestFn.java:130)
        at clojure.core$apply.invokeStatic(core.clj:646)
        at clojure.core$apply.invoke(core.clj:641)
        at pamela.unparser$unparse.invokeStatic(unparser.clj:528)
        at pamela.unparser$unparse.invoke(unparser.clj:527)
        at pamela.cli$unparse_model.invokeStatic(cli.clj:96)
        at pamela.cli$unparse_model.invoke(cli.clj:84)
        at clojure.lang.Var.invoke(Var.java:379)
        at pamela.cli$pamela.invokeStatic(cli.clj:312)
        at pamela.cli$pamela.doInvoke(cli.clj:254)
        at clojure.lang.RestFn.applyTo(RestFn.java:137)
        at clojure.core$apply.invokeStatic(core.clj:646)
        at clojure.core$apply.invoke(core.clj:641)
        at pamela.cli$_main.invokeStatic(cli.clj:328)
        at pamela.cli$_main.doInvoke(cli.clj:324)
        at clojure.lang.RestFn.applyTo(RestFn.java:137)
        at pamela.cli.main(Unknown Source)

```

**Comment by tmarble** [comment]
During...
1. **build** input is `*.pamela` and output is `*.ir.edn`
2. **unparse** input is `*.ir.edn` and output is `*.pamela`

The test file issue-147.pamela was added to demonstrate this functionality.

A buglet was found in handling the constant false in a cond-expr and that was fixed.
